language: php
sudo: false
php:
  - 7.3
install:
  - travis_retry composer install --prefer-dist
script:
  - vendor/bin/phpunit
after_script:
  - travis_retry php vendor/bin/coveralls -v
after_success:
  - >-
    test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" &&
    test $TRAVIS_PHP_VERSION = "7.1" && bash ./scripts/api.sh
cache:
  directories:
    - $HOME/.composer/cache
